DROP TABLE IF EXISTS ticker_info CASCADE;
DROP TABLE IF EXISTS all_signal_screener;

CREATE TABLE ticker_info(
    ticker VARCHAR(50) PRIMARY KEY,
    company VARCHAR(500),
    sector VARCHAR(250),
    industry VARCHAR(250),
    country VARCHAR(250),
    description TEXT
);

CREATE TABLE all_signal_screener(
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(50) REFERENCES ticker_info(ticker),
    date TIMESTAMP,
    market_cap BIGINT,
    p_e FLOAT,
    price FLOAT,
    change_percentage FLOAT,
    volume BIGINT,
    signals VARCHAR(255),
    no_of_signals INT,
    eps_ttm FLOAT,
    insider_own_percentage FLOAT,
    shs_outstand BIGINT,
    perf_week_percentage FLOAT,
    forward_p_e FLOAT,
    eps_next_y FLOAT,
    insider_trans_percentage FLOAT,
    shs_float FLOAT,
    perf_month_percentage FLOAT,
    income FLOAT,
    peg FLOAT,
    eps_next_q FLOAT,
    inst_own_percentage FLOAT,
    perf_quarter_percentage FLOAT,
    sales FLOAT,
    p_s FLOAT,
    eps_this_y_percentage FLOAT,
    inst_trans_percentage FLOAT,
    short_interest FLOAT,
    perf_half_y_percentage FLOAT,
    book_sh FLOAT,
    p_b FLOAT,
    eps_next_y_percentage_percentage FLOAT,
    roa_percentage FLOAT,
    target_price FLOAT,
    perf_year_percentage FLOAT,
    cash_sh FLOAT,
    p_c FLOAT,
    eps_next_5y_percentage FLOAT,
    roe_percentage FLOAT,
    range_from_52w FLOAT,
    range_to_52w FLOAT,
    perf_ytd_percentage FLOAT,
    dividend FLOAT,
    p_fcf FLOAT,
    eps_past_5y_percentage FLOAT,
    roi_percentage FLOAT,
    high_52w_percentage FLOAT,
    beta FLOAT,
    dividend_percentage FLOAT,
    quick_ratio FLOAT,
    sales_past_5y_percentage FLOAT,
    gross_margin_percentage FLOAT,
    low_52w_percentage FLOAT,
    atr FLOAT,
    employees BIGINT,
    current_ratio FLOAT,
    sales_q_q_percentage FLOAT,
    oper_margin_percentage FLOAT,
    rsi_14 FLOAT,
    volatility_w_percentage FLOAT,
    volatility_m_percentage FLOAT,
    optionable BOOLEAN,
    debt_eq FLOAT,
    eps_q_q_percentage FLOAT,
    profit_margin_percentage FLOAT,
    rel_volume FLOAT,
    prev_close FLOAT,
    shortable BOOLEAN,
    lt_debt_eq FLOAT,
    payout_percentage FLOAT,
    avg_volume BIGINT,
    recom FLOAT,
    sma20_percentage FLOAT,
    sma50_percentage FLOAT,
    sma200_percentage FLOAT,
    short_float_percentage FLOAT,
    short_float_ratio FLOAT,
    earnings_date DATE,
    earnings_timing VARCHAR(25)
);